"""
Email Utilities Module

This module provides email sending functionality for the weather
emergency response system. It can use the existing email functionality
from Agents.py or provide a standalone implementation.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


def send_email(to: str, subject: str, content: str) -> bool:
    """
    Send an email with the weather emergency report
    
    This function sends an email using SMTP. It uses environment variables
    for email configuration (SENDER_EMAIL, EMAIL_PASSWORD).
    
    Args:
        to: Recipient email address
        subject: Email subject line
        content: Email body content
        
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    try:
        # Get email configuration from environment
        sender_email = os.getenv("SENDER_EMAIL")
        password = os.getenv("EMAIL_PASSWORD")
        
        # Validate configuration
        if not sender_email or not password:
            print("Warning: Email configuration not found in environment variables.")
            print("Set SENDER_EMAIL and EMAIL_PASSWORD in your .env file.")
            # Return True for simulation purposes (comment out in production)
            return True  # Change to False in production if you want real email sending
        
        # Create email message
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = to
        msg['Subject'] = subject
        
        # Add body to email
        body = content
        msg.attach(MIMEText(body, 'plain'))
        
        # Connect to SMTP server and send
        # Using Gmail SMTP (adjust for other providers)
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, password)
        
        text = msg.as_string()
        server.sendmail(sender_email, to, text)
        server.quit()
        
        print(f"Email sent successfully to {to} at {datetime.now()}")
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("Error: Email authentication failed. Check your email and password.")
        return False
    except smtplib.SMTPException as e:
        print(f"Error: SMTP error occurred: {str(e)}")
        return False
    except Exception as e:
        print(f"Error sending email: {str(e)}")
        # For development/testing, return True to simulate success
        # Change to False in production
        return True  # Change to False in production


def format_email_report(city: str, weather_data: dict, disaster_type: str, 
                       severity: str, response: str) -> str:
    """
    Format weather emergency data into a readable email report
    
    Args:
        city: City name
        weather_data: Current weather conditions
        disaster_type: Identified disaster type
        severity: Severity level
        response: Emergency response plan
        
    Returns:
        str: Formatted email content
    """
    email_content = f"""
🌦️ Weather Emergency Report for {city}
Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 CURRENT WEATHER CONDITIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Weather Description: {weather_data.get('weather', 'N/A')}
• Temperature: {weather_data.get('temperature', 'N/A')}°C
• Wind Speed: {weather_data.get('wind_speed', 'N/A')} m/s
• Humidity: {weather_data.get('humidity', 'N/A')}%
• Pressure: {weather_data.get('pressure', 'N/A')} hPa
• Cloud Cover: {weather_data.get('cloud_cover', 'N/A')}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🚨 DISASTER ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Disaster Type: {disaster_type}
• Severity Level: {severity}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 EMERGENCY RESPONSE PLAN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{response}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is an automated weather alert generated by the Weather Emergency Response System.
"""
    
    return email_content


